### ISSUE TITLE
Wrong path in _hmg_resconfig.h

### ISSUE THREAD

**Issue by ujayadev** [Petewg/MgM#3]
In _hmg_resconfig.h, 
the path is defined as:
#define HMGRPATH i:\MiniguiM\minigui\resources

This causes problems, as say in my computer, I have cloned the repository in 'e' drive.  

My request is that the drive letter may be made dynamic.

Warm regards,

Jayadev

**Comment by Petewg** [comment]
hi Jayadev,

that's a known 'bug' but have not (yet) figured a good way to fix it.

any idea as to how to resolve it, is welcome!

thanks for your interest.

**Comment by ujayadev** [comment]
Hi Pete,

>>any idea as to how to resolve it, is welcome!

Please try with this command:

 

      ECHO #define HMGRPATH %MGROOT%\minigui\resources > %~d0\MiniguiM\minigui\resources\_hmg_resconfig.h

 

Warm regards,

 

Jayadev

**Comment by Petewg** [comment]
Fixed.
just delete _hmg_resconfig.h and it will be recreated with correct path during buildapp.bat
