### ISSUE TITLE
buildallib.bat

### ISSUE THREAD

**Issue by jkteg** [Petewg/MgM#9]
(I had already installed c:\hmg.3.4.4 version 18.07)

I have 
1. download MGM_master.zip en unzipped it in c:\MiniguiM
2 run MiniguiM\buildalllib.bat -> nothing happend.

Then
copy c:\hmg.3.4.4\harbour to c:\miniguim\comp\harbour
also c:\hmg.3.4.4\mingw to c:\miniguim\comp\mingw
Now c:\miniguim\buildalllib.bat works.

(i kan also copy c:\hmg.3.4.4\harbour-64 to en c:\hmg.3.4.4-64 if i wish ;-)

**Comment by Petewg** [comment]
Hi,
you could also get/use the latest Harbour 
https://github.com/Petewg/MgM/tree/master/comp/harbour
and newer MinGW 7.2 version 
https://github.com/Petewg/MgM/tree/master/comp/mingw32
